import os
import json
import asyncio
import requests
import base64
import mimetypes
from http import HTTPStatus
from datetime import datetime

from dashscope import MultiModalConversation, Application, ImageSynthesis
import dashscope

# 以下为中国（北京）地域 url，
# 若使用新加坡地域的模型，需将 url 替换为：https://dashscope-intl.aliyuncs.com/api/v1
dashscope.base_http_api_url = 'https://dashscope.aliyuncs.com/api/v1'



class QwenRemote:
    def __init__(self):
        self.logger=None

        # 新加坡和北京地域的 API Key不同。
        # 获取API Key：https://help.aliyun.com/zh/model-studio/get-api-key
        # self.api_key = "sk-cc67df1a9ed248c792bc53b58ab77ba3"  # Doesn't work
        self.api_key = "sk-5857a06baafb454fb85288170ee68dc0"
        # self.api_key = "sk-e0f50dc301534b199f976f17b733ed55"   # Kan

        try:
            from logger.logger import LlamediaLogger
            self.logger = LlamediaLogger("QwenRemote").getLogger()

            self.logger.info(f"QwenRemote class initialized.")
        except ImportError as e:
            if self.logger:
                self.logger.error(f"Could not initialize QwenRemote class, error message: '{str(e)}'")
            else:
                print(f"[ERROR] Could not initialize QwenRemote class, error message: '{str(e)}'")


    def encode_file(
            self, 
            image_filepath: str=""
        ):
        """
        Use Base64 to encode an image file for communication.
        
        Args:
            filepath (str): The input filepath to encode,
                following suffices are supported '.png', '.jpg', '.jpeg', '.bmp', '.gif'.
        Returns:
            Return a string with format of 'data:{mime_type};base64,{base64_data}',
                if return an empty string, it means something goes wrong when encoding.
        """                
        mime_type, _ = mimetypes.guess_type(image_filepath)
        if not mime_type or not mime_type.startswith("image/"):
            warn_msg = f"encode_file(), the input image_filepath is not a valid image file."
            self.logger.warn(warn_msg)
            return ""

        try:
            with open(image_filepath, "rb") as image_file:
                encoded_string = base64.b64encode(
                    image_file.read()).decode('utf-8')
            return f"data:{mime_type};base64,{encoded_string}"
        
        except IOError as e:
            warn_msg = f"encode_file(), cannot read the input image file '{image_filepath}'."
            warn_msg += f"The error message is: \n\t '{str(e)}'"
            self.logger.warn(warn_msg)
            return ""


    def download_image(
            self, 
            image_url: str="", 
            download_filepath: str=""
        ):
        """
        Given a URL 'image_url' of the image generated by Qwen AI model, 
        download it and save it to 'download_filepath'.
        
        Args:
            image_url (str): The URL of the image generated by Qwen AI model. 
            download_filepath (str): The filepath where to save the downloaded image.
        """          
        if os.path.isfile(download_filepath):
            os.remove(download_filepath)

        try:
            response = requests.get(
                image_url, 
                stream=True, 
                timeout=300   
            )  

            # If HTTP status code is not 200, raise an exception. 
            response.raise_for_status()  

            with open(download_filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)

            info_msg = f"download_image(), the image has been downloaded from '{image_url}', "
            info_msg += f"\n\t and saved to '{download_filepath}'."
            self.logger.info(info_msg)

        except requests.exceptions.RequestException as e:
            warn_msg = f"download_image(), cannot download the image from '{image_url}', "
            warn_msg += f"the error message is, \n\t'{str(e)}'."
            self.logger.warn(warn_msg)


    def qwen_image_edit(
            self, 
            prompt: str="",
            image_list: list=[],
            download_filepath: str=""
        ):
        """
        A remote call to the 'qwen-image-edit' model on the Alibaba Bailian AI platform,
        and download the AI generated image and save it to 'download_filepath'.
        
        Args:
            prompt (str): The input prompt.
            image_list (list): A list of image filepaths to upload to the AI model.
            download_filepath (str): The filepath where to save the downloaded image.
        """    
        message_content = [{"text": prompt}]

        for image_filepath in image_list:
            image = self.encode_file(image_filepath)
            message_content.append({"image": image})

        messages = [
            {
                "role": "user",
                "content": message_content
            }
        ]

        # 模型仅支持单轮对话，复用了多轮对话的接口
        response = MultiModalConversation.call(
            api_key=self.api_key,
            model="qwen-image-edit",
            messages=messages,
            stream=False,
            watermark=False,
            negative_prompt=" "
        )        
        

        if response.status_code == 200:
            # 如需查看完整响应，请取消下行注释
            # print(json.dumps(response, ensure_ascii=False))
            # print("输出图像的URL:", response.output.choices[0].message.content[0]['image'])
            image_url = response.output.choices[0].message.content[0]['image']

            info_msg = f"qwen_image_edit(), the URL of the generated image is '{image_url}'. "
            info_msg += f"You can download the image from there."
            self.logger.info(info_msg)

        else:
            warn_msg = f"qwen_image_edit(), the 'qwen-image-edit' doesn't respond successfully. "
            warn_msg += f"\n\t HTTP status code: {response.status_code}, "
            warn_msg += f"error message: '{response.message}'. "
            warn_msg += f"\n\t Reference: https://help.aliyun.com/zh/model-studio/developer-reference/error-code"
            self.logger.warn(warn_msg)
            image_url = ""

        if len(image_url) > 0:
            if os.path.isfile(download_filepath):
                os.remove(download_filepath)

            self.download_image(
                image_url=image_url, 
                download_filepath=download_filepath               
            )

            info_msg = f"qwen_image_edit(), A remote call to the 'qwen-image-edit' model has completed successfully, "
            info_msg += f"\n\t the image generated by the AI model has been downloaded and saved to '{download_filepath}'."
            self.logger.info(info_msg)
                        


    def usage_sample(self):
        project_dir = f"/home/robot/movie_blender_studio"
        input_image_filepaths = [
            f"{project_dir}/input/lynda.jpeg",
            f"{project_dir}/input/greenscreen_02.png",
            f"{project_dir}/input/opera_house_inside.jpeg",
            f"{project_dir}/input/opera_house_outside.jpeg"
        ]
        output_image_filepaths = [
            f"{project_dir}/output/lynda.jpeg",
        ]

        prompt_sentences = [
            f"Please extract human subject from the input image. ",
            f"And convert the pixels in the background to green, with alpha=0 (transparent)."
        ]

        prompt = f"{prompt_sentences[0]}{prompt_sentences[1]}"

        self.qwen_image_edit(
            prompt=prompt,
            image_list=[input_image_filepaths[0]],
            download_filepath=output_image_filepaths[0]
        )


    @staticmethod
    def run_demo():
        qwen_model = QwenRemote()
        qwen_model.usage_sample()

if __name__ == "__main__":
    QwenRemote.run_demo()




